name: build

on: [push, pull_request]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install pytest flake8 pytest-cov flask pyyaml
    - name: Test
      run: |
        pytest --cov=systems --cov-branch --cov-report=xml -v .
        flake8 --ignore=E402,W503 .
    - uses: codecov/codecov-action@v1
